name: Third
on:
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/qorkflows/*"

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Output Github Context
        run: echo "${{ toJSON(github.event) }}"
